- name: Escenario 1 - Viaje corto de naturaleza (3 días)
  budget: Económico
  travel_type: Pareja
  interests:
    - Naturaleza
    - Clima agradable
  duration_days: 3
  user_input: "Queremos visitar zonas verdes, parques naturales o jardines botánicos cerca de Brisbane."
  expected_relevant_docs:
    - "Brisbane#Descripción General"
    - "Brisbane#Principales Atracciones"
    - "Brisbane#Clima"
  evaluate_retrieval_docs: true

- name: Escenario 2 - Viaje cultural de 7 días
  budget: Medio
  travel_type: Individual
  interests:
    - Cultura
    - Historia y curiosidades
    - Turismo urbano
  duration_days: 7
  user_input: "Quiero explorar ciudades históricas con museos y sitios de interés cultural, especialmente en Melbourne."
  expected_relevant_docs:
    - "Melbourne#Descripción General"
    - "Melbourne#Principales Atracciones"
    - "Melbourne#Eventos y Festivales"
    - "Melbourne#Datos Curiosos"
  evaluate_retrieval_docs: true

- name: Escenario 3 - Viaje familiar temático (5 días)
  budget: Alto
  travel_type: Familia
  interests:
    - Aventura
    - Transporte público
    - Naturaleza
  duration_days: 5
  user_input: "Buscamos actividades divertidas y seguras para niños en contacto con la naturaleza. Nos movemos en transporte público."
  evaluate_retrieval_docs: false


- name: Escenario 4 - Viaje sin intereses definidos (4 días)
  budget: Económico
  travel_type: Mochilero
  interests: []
  duration_days: 4
  user_input: "Solo quiero un itinerario barato para recorrer varias ciudades por mi cuenta."
  evaluate_retrieval_docs: false
