presupuestos:
  - Económico
  - Medio
  - Alto

tipos_viaje:
  - Individual
  - Pareja
  - Familia
  - Mochilero

intereses:
  - Naturaleza
  - Playas
  - Cultura
  - Aventura
  - Gastronomía
  - Festivales y eventos
  - Turismo urbano
  - Clima agradable
  - Viaje económico
  - Transporte público
  - Historia y curiosidades